# Generated by Django 3.1.7 on 2021-03-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isComplete',
            new_name='complete',
        ),
    ]
