# Generated by Django 3.1.7 on 2021-03-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210310_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_str',
            field=models.SlugField(blank=True),
        ),
    ]
