# Generated by Django 3.1.7 on 2021-03-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210310_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='../static/images/user_icon.png', upload_to='../static/images/user_profile_pics'),
        ),
    ]
