# Generated by Django 3.1.7 on 2021-03-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_slug_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='../images/user_icon.png', upload_to='../images'),
        ),
    ]
