# Generated by Django 3.1.7 on 2021-03-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210312_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='../images/user_icon.png', upload_to='../images'),
        ),
    ]
