# Generated by Django 3.1.7 on 2021-03-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_unit',
            field=models.IntegerField(default=0),
        ),
    ]
