# Generated by Django 3.1.7 on 2021-03-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210313_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='../images/user_profile_pics/user_icon.png', upload_to='../images/user_profile_pics'),
        ),
    ]
