# Generated by Django 3.1.7 on 2021-03-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210313_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='../images/user_icon.png', upload_to='../images'),
        ),
    ]
