# Generated by Django 3.1.7 on 2021-03-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productviewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productviewcount',
            name='last_viewing',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
