# Generated by Django 3.1.7 on 2021-04-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_response_statement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='Statement',
        ),
    ]
