# Generated by Django 3.1.7 on 2021-04-05 07:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210403_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 5, 7, 18, 41, 759164, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to='store.customer'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_type',
            field=models.CharField(choices=[('sale', 'Sales'), ('auction', 'Auctions')], default='sale', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
