# Generated by Django 3.1.7 on 2021-04-05 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210405_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 5, 10, 58, 41, 103244, tzinfo=utc), null=True),
        ),
    ]
