# Generated by Django 3.1.7 on 2021-04-09 05:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210405_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 9, 5, 15, 54, 397493, tzinfo=utc), null=True),
        ),
    ]
