# Generated by Django 3.1.7 on 2021-04-09 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210409_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 9, 5, 25, 3, 482887, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='estimated_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
