# Generated by Django 3.1.7 on 2021-04-09 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210409_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 9, 5, 33, 34, 577269, tzinfo=utc), null=True),
        ),
    ]
