# Generated by Django 3.1.7 on 2021-04-09 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210409_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_period',
            field=models.DurationField(blank=True, default=datetime.datetime(2021, 4, 9, 5, 34, 48, 27744, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 9, 5, 34, 48, 27564, tzinfo=utc), null=True),
        ),
    ]
