# Generated by Django 3.1.7 on 2021-04-09 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210409_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_period',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 9, 5, 37, 12, 211419, tzinfo=utc), null=True),
        ),
    ]
