# Generated by Django 3.1.7 on 2021-04-14 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210414_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 14, 13, 29, 23, 373237, tzinfo=utc), null=True),
        ),
    ]
