# Generated by Django 3.1.7 on 2021-04-14 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210414_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidder',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='bidder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 14, 14, 6, 55, 595611, tzinfo=utc), null=True),
        ),
        migrations.AlterOrderWithRespectTo(
            name='bidder',
            order_with_respect_to=None,
        ),
    ]
