# Generated by Django 3.1.7 on 2021-04-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20210409_1547'),
        ('store', '0026_auto_20210415_0006'),
    ]

    operations = [
    ]
