# Generated by Django 3.1.7 on 2021-04-17 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20210417_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='store.customer')),
                ('product', models.ManyToManyField(blank=True, related_name='wishlist_product', to='store.Product')),
            ],
        ),
    ]
