# Generated by Django 3.1.7 on 2021-04-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug_str',
            field=models.SlugField(blank=True),
        ),
    ]
