# Generated by Django 3.1.7 on 2021-04-18 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_customer_slug_str'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='store.customer'),
        ),
    ]
