# Generated by Django 3.1.7 on 2021-04-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20210417_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageUri',
            field=models.TextField(blank=True),
        ),
    ]
