# Generated by Django 3.1.7 on 2021-04-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20210418_1943'),
        ('store', '0031_auto_20210417_2220'),
    ]

    operations = [
    ]
